---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

```{r, message=FALSE, echo=FALSE}
library("tidyverse")
```


# PFTCFunctions

<!-- badges: start -->
<!-- badges: end -->

The goal of PFTCFunctions is to create unique hashcodes for each individual leaf (envelope) from the Plant Functional Trait Course.

```{r, echo = FALSE}
data.frame(Country = c("Peru", "Peru", "Svalbard", "Peru"),
           seed = c(1, 1, 32, 6),
           Campaign = c("PFTC3", "Puna", "PFTC4", "PFTC5")) %>% 
  knitr::kable()
```


## Installation

You can install PFTCFunctions from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("remotes")
remotes::install_github("Plant-Functional-Trait-Course//PFTCFunctions")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(PFTCFunctions)
## create list with all envelope codes. And show the first five values
all_codes <- get_PFTC_envelope_codes(seed = 1)
all_codes$hashcode[1:5]
```



## Location of PFTC data

```{r, echo = FALSE}
data("PFTC_data_location")

PFTC_data_location %>% 
  select(Country, DataType, Remark) %>% 
  knitr::kable()
```
